name: KRTEST
favicon: null
layout_spectrum: 0.1961989626288414
typography_spectrum: 0.19792858022265136
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6788974262308329
  lightness: 0.48602632246911526
  saturation: 0.2866491295862943
  rhythmicContrast: 0.8415887395385653
purpose: []
